### ISSUE TITLE
high CPU usage / lagging cursor on large documents

### ISSUE THREAD

**Issue by dhrv** [medo64/Render-CRLF#1]
In larger documents (in my example a 500 KB plaintext file) there is a noticable and increasing delay between fast keyboard input and the rendering on the screen. CPU usage goes up and eventually there is a "program not responding" warning. I have narrowed down this problem to your extension (which is great btw!) and CPU profiling shows this function to cause the high CPU usage: [vscode.workspace.onDidChangeTextDocument()](https://github.com/medo64/Render-CRLF/blob/b8f5d5c5f72fab6575f9dcdf2eaf9d5ab78fb42b/out/extension.js#L111)

In my research for CRLF extensions I noticed [this one from sohamkamani](https://github.com/sohamkamani/code-eol/commit/19fa54d5367164d82a34175f77f9f264ba120995) which has a lag fix built in with the latest commit, maybe this can be implemented in your extension as well? Another idea could be a simple `setTimeout()` wrapping of the `vscode.workspace.onDidChangeTextDocument()` function

Attachments:
[Code.exe --status](https://github.com/medo64/Render-CRLF/files/2900797/Code.exe.status.txt)
[CPU profiling](https://github.com/medo64/Render-CRLF/files/2900800/CPU-20190225T132346.202Z.cpuprofile.txt)
![screen capture](https://user-images.githubusercontent.com/17747160/53342704-e53fcd80-390e-11e9-875d-a2501da5225d.gif)

**Comment by medo64** [comment]
Thanks, I'll look into this.

**Comment by medo64** [comment]
Just a quick update - I've checked code from extension you mentioned and my current code does the exactly same thing as his. Moreover, I tested his extension also and I get the same lag as with mine.

That said, I believe there is a bit of place for improvement here and I will look into it over weekend. Unfortunately, I don't see an easy win here. :(

**Comment by medo64** [comment]
Please check the latest version (1.3.0). As I couldn't improve the existing parsing by much, I completely refactored it so that only visible portions are processed. This will bring a *huge* speed-up for large documents.

**Comment by dhrv** [comment]
Sorry for the late response (I'm sick). I confirm the problem is fixed with v1.3.0 and everything runs very smoothly now. Thank you for taking the time!
