### ISSUE TITLE
Line endings are not correct rendered

### ISSUE THREAD

**Issue by pascalre** [medo64/Render-CRLF#13]
I have a file which uses CRLF as default line encoding. Most of the lines are wrapped with an CRLF, but the forelast line has a CR and the last line has a LF. The plugin does not render the line endings correct.

How it looks in vscode:
![preview-in-vscode](https://user-images.githubusercontent.com/23454966/99778081-7e673c80-2b13-11eb-8c39-9510ed1339d1.PNG)
How I expected it to look:
![preview-in-notepad++](https://user-images.githubusercontent.com/23454966/99778082-7e673c80-2b13-11eb-94d3-4d513290c1fe.PNG)

The extension settings are:
```
    "code-eol.newlineCharacter": "¬",
    "code-eol.returnCharacter" : "¤",
    "code-eol.crlfCharacter"   : "¤¬",
```

Attachements:
- [settings.txt](https://github.com/medo64/Render-CRLF/files/5572252/settings.txt)

**Comment by medo64** [comment]
Hi,

This is a known issue and Visual Studio Code limitation (see [issue 127](https://github.com/Microsoft/vscode/issues/127)). Unfortunately, unless it's solved in VSCode, there is nothing I can do about it. :(
