### ISSUE TITLE
Sometimes leaves behind a trail of actual characters

### ISSUE THREAD

**Issue by GruelingPine185** [medo64/Render-CRLF#16]
I really like this extension because it is incredibly helpful, but the reason why I'm here is because of an annoying bug that that occurs occasionally. Every now and then, the gray whitespace characters turn yellow and somehow become actual characters as if I was the one to type them. It becomes irritating when I'm compiling my source code and it throws unexpected token errors. 
 
 This is how it looks when it works as expected:

<img width="559" alt="Screen Shot 2021-07-19 at 7 33 30 PM" src="https://user-images.githubusercontent.com/66073333/126240454-5df5a5c0-4482-4edc-b377-0ff756678773.png">

This is one small section of code I came across which had this problem. As you can see, it not only causes compiler issues, as mentioned, but it also effects syntax highlighting. Turning the extension off and on doesn't work btw.

<img width="563" alt="Screen Shot 2021-07-19 at 7 27 36 PM" src="https://user-images.githubusercontent.com/66073333/126240179-8a9f4f35-fd9a-4ea7-aa03-780278ab80ed.png">

If it helps, this is my current VSCode version:

>Version: 1.58.2 (Universal)
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:09:06.581Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.1.0

**Comment by medo64** [comment]
Hm, not sure about it - it might be interaction with some other extension. Changing color to orange is expected and controlled by `code-eol.highlightExtraWhitespace` and with `code-eol.highlightNonDefault`. If you set it to false, coloring should dissapear.

That said, I don't see anything in code doing any changes to nature of whitespaces - only coloring them.

**Comment by pm4rcin** [comment]
@GruelingPine185 isn't it something like [that](https://code.visualstudio.com/updates/v1_63#_unicode-highlighting)? I guess it was fixed recently.

**Comment by GruelingPine185** [comment]
That's a possibility, but I'm not sure. I haven't had any problems recently, so i'll give the extension another try and see about it soon.

**Comment by GruelingPine185** [comment]
I haven't had any issues so far :)
Syntax highlighting and warnings are normal, and no sign of extra characters.

**Comment by pm4rcin** [comment]
Good to hear that. Let's close issue for now.

**Comment by medo64** [comment]
Thank you both for all the research.
