### ISSUE TITLE
Does not correctly show mixed line endings

### ISSUE THREAD

**Issue by mtschoen-unity** [medo64/Render-CRLF#19]
The Unity game engine shows a warning sometimes when it encounters a file with both LF and CRLF line endings. I was trying to use this extension to check which lines were using what type of EOL and found that every line was marked with CRLF in this case. I know which lines were using LF, because if I convert the whole file to LF, and then back to CRLF, I can see the lines that changed by viewing the diff in the Fork git UI.

It looks like maybe this just checks the first EOL character and renders all of them the same. Maybe this is done as an optimization? Perhaps there is some other reason for what I am seeing?

**Comment by medo64** [comment]
Hi,

Unfortunately, this is a known [Visual Studio Code issue](https://github.com/Microsoft/vscode/issues/127) that I cannot address. Visual Studio Code normalizes the line endings upon loading the file and thus my extension will never see multiple line endings. There is no workaround at this time. :(

**Comment by mtschoen-unity** [comment]
Huh! That's interesting. Thanks for the info 👍

**Comment by DecimalTurn** [comment]
Porential workaround?
https://github.com/Steditor/vsce-line-endings/pull/4

**Comment by medo64** [comment]
> Potential workaround? [Steditor/vsce-line-endings#4](https://github.com/Steditor/vsce-line-endings/pull/4)

I checked pull request you linked but, since it reads file directly, it will only work on state as it was when file was saved. Thus, as soon as one edits file, all that work is invalid. Furthermore, to do it properly, one would need to essentially implement all file encodings that might cause false positives.

**Comment by DecimalTurn** [comment]
Would that approach be at least good enough to provide an alert when opening the file to warn that line endings were normalized? Regarding the encoding problem, that's indeed something to think of, but perhaps a warning that is a false positive is less problematic than making unwanted EOL normalizations without noticing it.

**Comment by medo64** [comment]
> Would that approach be at least good enough to provide an alert when opening the file to warn that line endings were normalized?

It would. However... that would require reading the whole file. The way extension is written, it never works with the whole file as to keep its performance when working with remote and/or large files.

Now, adding this as optional functionality for warning purposes only might be possible but I would need to look further into that.
