### ISSUE TITLE
Want to work together?

### ISSUE THREAD

**Issue by jeff-hykin** [medo64/Render-CRLF#2]
I've got an [extension](https://github.com/jeff-hykin/code-eol) I wrote awhile ago that has similar functionality (it has more eol customization, but missing highlightNonDefault). If you want I'll add you as a contributor, that way people can get all features instead of having to choose, and if we add optimizations everyone would get them.

I really like the features you have; using `editorWhitespace.foreground`, `errorForeground`, and the option for `highlightNonDefault`. I plan on adding those to [code eol](https://github.com/jeff-hykin/code-eol) next week, but I wanted to reach out first since you're the real author of those ideas. I also didn't know about `onDidChangeConfiguration` so I'll be switching to that as well instead of requiring a reload. [code eol](https://github.com/jeff-hykin/code-eol) has a decent user base and I'm sure they'd appreciate the added functionality and better default colors.

Let me know if theres anything you'd like to change, I don't have many preferences for name/icon/coding style etc, I just think it'd be nice to have one extension with all the line ending features.

**Comment by medo64** [comment]
Hi, I actually know of your extension as it was inspiration for me to start playing with creating one myself. My first parsing code was actually based on your approach to parsing until the last version. I am glad you like some features it has and of course you can use them in your extension. Goal of my extension is to be rather simple in nature and I don't believe there will be many further updates while your has a bit more ambitious goal. I might come in over weekend with a pull request or two. :)

**Comment by jeff-hykin** [comment]
Sounds good! :) Thanks for the quick response.
