### ISSUE TITLE
EOL decoration is always useful when "wordWrap" is "on"

### ISSUE THREAD

**Issue by ytomino** [medo64/Render-CRLF#20]
Hello.
I love the editors that can show EOL.
It seems fashionable to emphasis spaces at end of each line instead of showing EOL in the recent editors.
However, EOL decoration is especially useful when "wordWrap" is "on".
I would like to turn on EOL decoration for files where "wordWrap" is "on" even if "renderWhitespace" is "boundary" (that is my preferred setting).
Could you add some kind of option?

I have wrote the draft patch: https://github.com/ytomino/Render-CRLF/commit/6df738e0389030853b01a8d243c3ba28cadb2c0c

This extension is well kept in order and very easy to understand to me.
Thanks.

**Comment by ytomino** [comment]
Thank you for reviewing in https://github.com/ytomino/Render-CRLF/commit/6df738e0389030853b01a8d243c3ba28cadb2c0c.
The fixing commit https://github.com/ytomino/Render-CRLF/commit/4db237d87210be034a3914e1e1f6c07a6d04c8f0 and the squashed https://github.com/ytomino/Render-CRLF/commit/602a07d3430cca601753bf894feafb773f3b85f2 .

**Comment by medo64** [comment]
Looks good. Please make it a pull request and I'll take it in. Mind you I will probably hide behavior behind a setting as it might not be desirable in some circumstances. I will probably wrap it up on weekend.

**Comment by ytomino** [comment]
Okay. I made #21.

**Comment by medo64** [comment]
Thanks for contribution!

**Comment by medo64** [comment]
After some thinking, I believe it would confuse some users why EOL would be shown on wordwrap even when they are not choosing to view whitespace. Thus I have added parameter `code-eol.forceShowOnWordWrap` that would control the behavior you want. If parameter is true, it will always show EOL characters, irregardless of the render whitespace setting.

Thanks again for contributing!
