### ISSUE TITLE
Extension doesn't work and its "view" context menu entries are not present

### ISSUE THREAD

**Issue by abstractionmage** [medo64/Render-CRLF#26]
I installed the extension and restarted VSCode, yet no line endings are being rendered. VSCode's `view` context menu doesn't have any new entries either, as opposed to the gif in the readme showing the two new `View -> Render Whitespace` and `View -> Render Control Characters` context menu options.

![Screenshot_20221230_103920](https://user-images.githubusercontent.com/37195767/210056061-18d6b53c-1ec1-4a70-8e9a-ec7bcd6ecf87.png)

**Comment by medo64** [comment]
This is not due to the extension but due to VSCode moving this under View, Appearance submenu with the latest version.
I will update screenshots.
