### ISSUE TITLE
Trailing whitespace is gray with "Highlight Extra Whitespace" enabled on VSCode 1.75 (Windows)

### ISSUE THREAD

**Issue by mrstecklo** [medo64/Render-CRLF#27]
Hi,
I've recently updated VSCode and trailing whitespace is no longer highlighted.
I've tried disabling/enabling plugin, reinstalling it, but nothing helps.
The issue is definitely related to the update of VSCode, but I don't know the exact version that introduced it

**Comment by taesungh** [comment]
Wow, I knew this feature existed long ago but never noticed when it stopped working until I was digging through the settings again today. Seems that with microsoft/vscode#168732 (Add a new rendering technique for whitespace), the whitespace rendering was switched from middle dot characters to an SVG overlay of circles, so adding a text color decoration no longer has any effect.

I think a temporary workaround would be making the decoration change the background color instead by modifying [out/extension.js:108](https://github.com/medo64/Render-CRLF/blob/main/out/extension.js#L108) to

```javascript
extraWhitespaceDecorationType = vscode.window.createTextEditorDecorationType({ backgroundColor: themeColorError })
```

**Comment by medo64** [comment]
Thank you. Will add it tomorrow and release new version!

**Comment by taesungh** [comment]
Upon further exploration, I found there is an `editor.experimentalWhitespaceRendering` setting which provides the old behavior when set to "off" at the cost of the issues the new rendering addressed. For compatibility purposes, it might be better to conditionally change the extra whitespace decoration style based on this setting?

Additionally, upon actual use, the background color highlight I proposed is a bit too distracting when in the middle of typing out a line. I instead tried a dotted strikethrough and found it to be subtler and preferred in this regard.
```javascript
{ textDecoration: "line-through dotted var(--vscode-editorError-foreground)" }
```

**Comment by medo64** [comment]
fair enough  :)
Thanks for the code!

Since in the pull request you mention to hold off, I'll do so until you tell me you're happy with the code.

**Comment by taesungh** [comment]
Added what I think should work out, ready for review.

**Comment by taesungh** [comment]
Sorry, should have linked from #28, but I think this issue can be closed now.

**Comment by medo64** [comment]
New version pushed out. Thank you!
