### ISSUE TITLE
Possibly compatible with GitLens and other decorators

### ISSUE THREAD

**Issue by peter-kehl** [medo64/Render-CRLF#29]
Thank you for Render-CRLF, Josip.

1. Please have a look at https://github.com/microsoft/vscode/issues/33852. It sounds like the conflicts with GitLens etc. may be gone. (I can't confirm, I don't use them).
2. If the problem still exists, please check the Markdown of the link to https://github.com/microsoft/vscode/issues/33852 from README.md. On GitHub it renders OK. But on https://marketplace.visualstudio.com/items?itemName=medo64.render-crlf it renders bad: `[issue [#33852](https://github.com/medo64/render-crlf/issues/33852)](https://github.com/microsoft/vscode/issues/33852)`, and, even worse, the first part is a link to a non-existing issue number `33852` in this (Render-CRLF) repo.

**Comment by its-miroma** [comment]
Unfortunately, it appears that Render-CRLF's EOL character
is shown after GitLens.

![VS Code screenshot showing Git Lens and Render-CRLF conflict](https://github.com/medo64/Render-CRLF/assets/136986257/f9aebfce-18f3-4ea2-9cfa-47036c41d0e3)

**Comment by its-miroma** [comment]
Actually, the problem was fixed after a reload...
That's weird.

![VS Code screenshot with GitLens and Render-CRLF, and there's no conflict](https://github.com/medo64/Render-CRLF/assets/136986257/3225750f-61b4-46c5-92ce-f447ddcdf8b0)
