### ISSUE TITLE
Not affected new "editor.renderWhitespace" option

### ISSUE THREAD

**Issue by kanlukasz** [medo64/Render-CRLF#3]
Hi,

Thank you for this very useful add-on.
I have one problem.

If i set VSCode option `"editor.renderWhitespace"` to `"selection"`, your addon doesn't work in this way.
Arrows are still visible all the time (not only when the text is selected)

Is there any chance to fix this?

**Comment by medo64** [comment]
Yep, I'll look into that. However, won't have time this weekend so fix will be in probably the week after.

**Comment by medo64** [comment]
Fixed in version 1.4.6
