### ISSUE TITLE
Is this extension can correctly render mixed line endings?

### ISSUE THREAD

**Issue by Mingun** [medo64/Render-CRLF#33]
Today I got a merge conflict in my git working copy that was related to different line endings. It seems that part of lines ended with CR+LF and part with LF and the difference in some lines created a merge conflict. But when I tried this extension it showed me that all lines ended with the same sequence, which is configured in VSCode. I'm doubt that this was true, because then why git (GitKraken actually) shows me the difference?

So the question: did you rended _actual_ line endings or just the _configured_ one?

**Comment by medo64** [comment]
Unfortunately, no VS Code extension can do mixed endings because VS Code itself doesn't support the same (see issue  [`microsoft/vscode#127`](https://github.com/microsoft/vscode/issues/127)) :(
