### ISSUE TITLE
Overrides GitLens's blame in selected line

### ISSUE THREAD

**Issue by PierreZiegler** [medo64/Render-CRLF#5]
Normally GitLens displays the author, date and commit message in the selected line like this:

```css
min-width: 90px;        You, 2020-04-09 Uncommitted changes
```

With Render Line Endings installed it shows this:

```css
min-width: 90px;        ↓
```

Expected behavior:

```css
min-width: 90px;↓        You, 2020-04-09 Uncommitted changes
```

**Comment by ljubadr** [comment]
Same here - I just installed this extension and GitLens blame disappeared...

**Comment by medo64** [comment]
This is a know [VSCode issue](https://github.com/microsoft/vscode/issues/91185). Essentially two extensions that create the same decoration have their conflict "solved" by browser determining order of application.

That said, I will check if I can make it so GitLens "wins" as it only shows it's output in the current line. Based on VSCode documentation and tickets I don't believe I can provide both extensions working.

**Comment by medo64** [comment]
I have added two workarounds.

1) I reworked how decorations are added so now it should either show GitLens or end-of-line markings - not both. On my system GitLens overrides end-of-line extension for current line so essentially you'll get GitLens on current line and EOL markings on every other.

2) I added a setting to change where EOL markings are rendered so this extension is not in conflict with GitLabs. Setting it will unfortunately remove EOL markings from empty lines but it will allow using this extension and GitLens together. To set it you can add the following entry in config.

    "code-eol.decorateBeforeEol": true,

Please note that both these workarounds require version 1.5.3 (that should be out as I write this).

**Comment by ljubadr** [comment]
I can confirm that this solved the issue for me, thank you for this quick fix :)

I didn't even have to use the new setting `"code-eol.decorateBeforeEol": true`

Awesome plugin :)

**Comment by medo64** [comment]
Thanks for verifying the fix! Glad it works for you!

**Comment by PierreZiegler** [comment]
Thanks! The update works great!

I've tried the setting `"code-eol.decorateBeforeEol": true` as well and it works good too.
I'll stick with the default setting, so I can technically see the line endings in all lines, but it's good to have the option!

**Comment by medo64** [comment]
Awesome, glad it works!
