### ISSUE TITLE
Doesn't work with per file type settings

### ISSUE THREAD

**Issue by markonius** [medo64/Render-CRLF#7]
Hi! Nice extension.

I have whitespace enabled for markdown files (`"[markdown]": {"editor.renderWhitespace": "on"}`), and the extension doesn't work. If I turn whitespace on globaly, it works.

**Comment by medo64** [comment]
Implemented in commit [#8da6e76](https://github.com/medo64/Render-CRLF/commit/8da6e76aa716a299366d36ba8815bee2d75f38f6)

**Comment by medo64** [comment]
Available with 1.5.5

**Comment by markonius** [comment]
That was quick...
Hvala
