### ISSUE TITLE
Glyphs don't hide with toggle whitespace

### ISSUE THREAD

**Issue by gitcabezon** [medo64/Render-CRLF#9]
LF glyphs aren't properly hiding when toggling whitespace -- they stay visible while the other whitespace properly toggles.  Switching to another editor in the same window and then back works to hide the glyphs.

Version: 1.47.2
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:18:50.054Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

**Comment by medo64** [comment]
Sorry, this bug was introduced while refactoring extension to work with file compare dialog properly.
Will fix it in a few.

**Comment by medo64** [comment]
Fixed in commit [#c92b0d9](https://github.com/medo64/Render-CRLF/commit/c92b0d9a092d5170f3e4fcd2d52197a2685ded0e).
Version 1.5.9 published.
